- hosts: all
  tasks:
    - name: copy env
      ansible.builtin.template:
        src: .env.example.j2
        dest: .env
        mode: 0644

    - name: Create a directory for cloud certificate
      ansible.builtin.file:
        path: .postgresql
        state: directory

    - name: Download a cloud certificate
      ansible.builtin.get_url:
        url: https://storage.yandexcloud.net/cloud-certs/CA.pem
        dest: .postgresql/root.crt
        mode: 0644

    - name: start redmine
      community.docker.docker_container:
        name: redmine
        image: redmine
        restart_policy: always
        state: started
        env_file: .env
        ports: "{{ app_port }}:3000"
