- hosts: all
  tasks:
    - name: Create config file
      ansible.builtin.template:
        src: .env.example
        dest: .env

    - community.docker.docker_container:
        name: redmine
        image: redmine
        restart_policy: always
        state: started
        env_file: .env
        ports:
          - 3000:3000
